# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 220ae0f3ea3c6525e87e9d162645bfd14f503963bb1f5d3692f381ed65013183b608524d2cd50ef1688847e2fdf8e9fb565ea8bcc50ad4b0bcbddfa41c63fe14

test:
  secret_key_base: 716db440a90f3d6d61efb1d4246bcb6ad9b8a52d0c5168532f4e4b1c47ce8412ccfd1497b52ca0f0b2874bf1734bc20835b1dfcafa4c71f554b057b984e316e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
